# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'games/libkdegames': '@same'
    'frameworks/karchive': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kjobwidgets': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kxmlgui': '@stable'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows']
